version: '2'

services:

  app:
    build: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /opt/docker/jenkins/volumes/app/var/jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
